In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5]
array = np.array(lista)
array

array([1, 2, 3, 4, 5])

In [3]:
lista2 = [[1,2,3], [4,5,6], [7,8,9]]
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
array2 = np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array_1 = np.arange(5)
array_1

array([0, 1, 2, 3, 4])

In [6]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.arange(5,30,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(3,9,35)

array([3.        , 3.17647059, 3.35294118, 3.52941176, 3.70588235,
       3.88235294, 4.05882353, 4.23529412, 4.41176471, 4.58823529,
       4.76470588, 4.94117647, 5.11764706, 5.29411765, 5.47058824,
       5.64705882, 5.82352941, 6.        , 6.17647059, 6.35294118,
       6.52941176, 6.70588235, 6.88235294, 7.05882353, 7.23529412,
       7.41176471, 7.58823529, 7.76470588, 7.94117647, 8.11764706,
       8.29411765, 8.47058824, 8.64705882, 8.82352941, 9.        ])

In [13]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(10)

array([0.89360638, 0.66170355, 0.90471411, 0.90085351, 0.69022389,
       0.46719466, 0.28685444, 0.81911357, 0.19385989, 0.23011145])

In [15]:
np.random.rand(2,5)

array([[0.46375439, 0.31887916, 0.6589113 , 0.70904769, 0.04796112],
       [0.29772168, 0.66306042, 0.6537419 , 0.23214417, 0.38191064]])

In [16]:
np.random.randn(10)

array([-0.63532052, -2.03711874, -1.60132035, -0.15857517,  1.40741234,
        2.16335246,  1.17331427,  0.03696037, -0.36613245,  1.49884268])

In [17]:
np.random.randn(2,5)

array([[-0.05069312, -0.33318659,  1.02510499,  0.41978565, -0.64007068],
       [-1.71418712,  0.48140663,  0.09895545, -0.09324353,  0.64810135]])

In [18]:
np.random.randint(10,15)

11

In [19]:
np.random.randint(1,50,5)

array([ 7, 13,  6, 25,  1])

In [20]:
array_2 = np.random.randint(1,300,30)
array_2

array([141, 110,  71,   6, 196, 243, 165, 170, 179, 262, 123, 207, 218,
        74, 161, 186, 286, 181, 261, 287,   9, 214, 162,   4, 116,  54,
       254, 105, 134, 205])

In [21]:
matriz = array_2.reshape(6,5)
matriz

array([[141, 110,  71,   6, 196],
       [243, 165, 170, 179, 262],
       [123, 207, 218,  74, 161],
       [186, 286, 181, 261, 287],
       [  9, 214, 162,   4, 116],
       [ 54, 254, 105, 134, 205]])

In [22]:
array_3 = np.random.randint(1,100,50)
array_3

array([73, 46, 82, 44,  2, 70, 67, 42,  3, 20, 12, 65, 34, 50, 30, 55, 92,
       29, 55, 31, 57, 72, 97, 40, 92, 28, 77, 64, 82, 88, 19,  6, 78, 18,
       84, 67, 55, 46, 54, 64, 88, 89, 82, 70, 22, 45, 45, 13, 17, 65])

In [23]:
Val_Max = array_3.max()
Val_Max

97

In [24]:
Pos_Val_Max = array_3.argmax()
Pos_Val_Max

22

In [25]:
Val_Min = array_3.min()
Val_Min

2

In [26]:
Pos_Val_Min = array_3.argmin()
Pos_Val_Min

4

In [27]:
array_4 = np.arange(0,10)
array_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
array_4[0]

0

In [29]:
array_4[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [30]:
array_4[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
array_4[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
array_4[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [33]:
copia = array_4.copy()
copia

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
copia[3] = 150
copia

array([  0,   1,   2, 150,   4,   5,   6,   7,   8,   9])

In [35]:
array_5 = np.array([[1,2,3],[4,5,6], [7,8,9]])
array_5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
array_5[0]

array([1, 2, 3])

In [37]:
array_5[:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
array_5[0][-1]

3

In [39]:
array_5[0,-1]

3

In [40]:
array_5[2,1]

8

In [41]:
array_5[:,1]

array([2, 5, 8])

In [42]:
array_5[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [43]:
arreglo = np.arange(1,16)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
condicion = arreglo > 5

In [45]:
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [46]:
arreglo[condicion]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
arreglo[arreglo > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
arreglo[arreglo < 4]

array([1, 2, 3])

In [49]:
arreglo[arreglo % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [50]:
arreglo + arreglo

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [51]:
arreglo - arreglo

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
arreglo * arreglo

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225])

In [53]:
arreglo / arreglo

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [54]:
((arreglo * 25) + 1)

array([ 26,  51,  76, 101, 126, 151, 176, 201, 226, 251, 276, 301, 326,
       351, 376])

In [55]:
np.sqrt(arreglo)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335])

In [56]:
np.max(arreglo)

15

In [57]:
ejercicio_1 = np.arange(10,40)
ejercicio_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [58]:
lista_reordenada = ejercicio_1.reshape(3,10)
lista_reordenada

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [59]:
lista_reordenada[0,9]

19

In [60]:
ejercicio_2 = np.random.randint(0,101,9)
ejercicio_2

array([55, 44, 48, 13, 40, 58, 69, 90,  7])

In [61]:
arreglo_ordenado = ejercicio_2.reshape(3,3)
arreglo_ordenado

array([[55, 44, 48],
       [13, 40, 58],
       [69, 90,  7]])

In [62]:
arreglo_ordenado[2,2]

7