In [5]:
import numpy as np

In [8]:
lista = [1,2,3,4,5]
array = np.array(lista)
array

array([1, 2, 3, 4, 5])

In [12]:
lista2 = [[1,2,3], [4,5,6], [7,8,9]]
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
array2 = np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
array_1 = np.arange(5)
array_1

array([0, 1, 2, 3, 4])

In [17]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.arange(5,30,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.linspace(3,9,35)

array([3.        , 3.17647059, 3.35294118, 3.52941176, 3.70588235,
       3.88235294, 4.05882353, 4.23529412, 4.41176471, 4.58823529,
       4.76470588, 4.94117647, 5.11764706, 5.29411765, 5.47058824,
       5.64705882, 5.82352941, 6.        , 6.17647059, 6.35294118,
       6.52941176, 6.70588235, 6.88235294, 7.05882353, 7.23529412,
       7.41176471, 7.58823529, 7.76470588, 7.94117647, 8.11764706,
       8.29411765, 8.47058824, 8.64705882, 8.82352941, 9.        ])

In [42]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [55]:
np.random.rand(10)

array([0.57018537, 0.5683426 , 0.22669796, 0.99894216, 0.30484068,
       0.93419603, 0.29636433, 0.24511701, 0.37593854, 0.8525249 ])

In [64]:
np.random.rand(2,5)

array([[0.48152755, 0.32762056, 0.13191328, 0.55502667, 0.43516067],
       [0.07318396, 0.05831416, 0.54853966, 0.01500014, 0.56698421]])

In [66]:
np.random.randn(10)

array([-0.15717827,  2.41200371,  0.164305  , -1.05063664,  0.86624498,
       -0.62391302, -0.27735145,  0.61662343, -0.69203397, -1.18682048])

In [67]:
np.random.randn(2,5)

array([[ 1.47283931, -0.50583294,  0.57675979,  1.0383091 ,  0.39586582],
       [ 0.86313233, -0.61208798,  0.29397155,  0.25780983, -1.81405961]])

In [77]:
np.random.randint(10,15)

14

In [78]:
np.random.randint(1,50,5)

array([ 6, 28, 15, 15, 43])

In [86]:
array_2 = np.random.randint(1,300,30)
array_2

array([ 62, 157,  12,  26,  47, 137,  59,   1, 171, 174, 232,  82, 265,
       264, 198,  34, 178, 202, 156, 287,  81,  64, 138, 193,  92, 169,
       100, 256,   2, 216])

In [88]:
matriz = array_2.reshape(6,5)
matriz

array([[ 62, 157,  12,  26,  47],
       [137,  59,   1, 171, 174],
       [232,  82, 265, 264, 198],
       [ 34, 178, 202, 156, 287],
       [ 81,  64, 138, 193,  92],
       [169, 100, 256,   2, 216]])

In [91]:
array_3 = np.random.randint(1,100,50)
array_3

array([57, 36, 31, 97, 93, 46, 62, 81, 62, 95,  9, 37, 88, 95,  9, 21, 65,
        7, 49, 53, 42, 41, 95, 85, 94, 92, 46, 34, 50, 63, 52, 39, 82, 75,
       23, 47, 76, 63, 94,  9, 92, 66, 21, 59, 47, 77, 66, 72, 90, 76])

In [93]:
Val_Max = array_3.max()
Val_Max

97

In [97]:
Pos_Val_Max = array_3.argmax()
Pos_Val_Max

3

In [94]:
Val_Min = array_3.min()
Val_Min

7

In [98]:
Pos_Val_Min = array_3.argmin()
Pos_Val_Min

17

In [104]:
array_4 = np.arange(0,10)
array_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
array_4[0]

0

In [108]:
array_4[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [109]:
array_4[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
array_4[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
array_4[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [112]:
copia = array_4.copy()
copia

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
copia[3] = 150
copia

array([  0,   1,   2, 150,   4,   5,   6,   7,   8,   9])

In [114]:
array_5 = np.array([[1,2,3],[4,5,6], [7,8,9]])
array_5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
array_5[0]

array([1, 2, 3])

In [120]:
array_5[:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
array_5[0][-1]

3

In [127]:
array_5[0,-1]

3

In [133]:
array_5[2,1]

8

In [140]:
array_5[:,1]

array([2, 5, 8])

In [149]:
array_5[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [152]:
arreglo = np.arange(1,16)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [153]:
condicion = arreglo > 5

In [154]:
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [155]:
arreglo[condicion]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [156]:
arreglo[arreglo > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [157]:
arreglo[arreglo < 4]

array([1, 2, 3])

In [159]:
arreglo[arreglo % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [160]:
arreglo + arreglo

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [161]:
arreglo - arreglo

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [162]:
arreglo * arreglo

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225])

In [163]:
arreglo / arreglo

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [168]:
((arreglo * 25) + 1)

array([ 26,  51,  76, 101, 126, 151, 176, 201, 226, 251, 276, 301, 326,
       351, 376])

In [169]:
np.sqrt(arreglo)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335])

In [170]:
np.max(arreglo)

15

In [173]:
ejercicio_1 = np.arange(10,40)
ejercicio_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [177]:
lista_reordenada = ejercicio_1.reshape(3,10)
lista_reordenada

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [191]:
lista_reordenada[0,9]

19

In [197]:
ejercicio_2 = np.random.randint(0,101,9)
ejercicio_2

array([23, 14, 49, 72, 36, 40, 71, 73, 21])

In [198]:
arreglo_ordenado = ejercicio_2.reshape(3,3)
arreglo_ordenado

array([[23, 14, 49],
       [72, 36, 40],
       [71, 73, 21]])

In [199]:
arreglo_ordenado[2,2]

21