In [3]:
import pandas as pd
import numpy as np

In [12]:
Asignaturas =  ['Matematicas', 'Fisica', 'Historia']
Notas = [9,9,8]

In [13]:
Serie = pd.Series(data = Notas, index=Asignaturas)

In [14]:
Serie

Matematicas    9
Fisica         9
Historia       8
dtype: int64

In [20]:
nota_fisica = Serie['Fisica']
nota_fisica

9

In [23]:
frase = print("La nota de fisica es un {}".format(nota_fisica))

La nota de fisica es un 9


## Ejercicio 2

In [36]:
ventas_enero = np.random.randint(100,500,3)
ventas_febrero = np.random.randint(100,500,3)
ventas_marzo = np.random.randint(100,500,3)

In [37]:
ventas_enero

array([205, 192, 123])

In [38]:
ventas_febrero

array([417, 160, 461])

In [39]:
ventas_marzo

array([346, 242, 340])

In [40]:
filas = ['ventas_enero', 'ventas_febrero', 'ventas_marzo']
columnas = ['oficina_1', 'oficina_2', 'oficina_3']
ventas = ([ventas_enero, ventas_febrero, ventas_marzo])

In [41]:
ventas

[array([205, 192, 123]), array([417, 160, 461]), array([346, 242, 340])]

In [42]:
dataframe = pd.DataFrame(ventas, filas, columnas)
dataframe

oficina_1  oficina_2  oficina_3
ventas_enero          205        192        123
ventas_febrero        417        160        461
ventas_marzo          346        242        340

In [51]:
VEO1 = dataframe['oficina_1']['ventas_enero']

In [52]:
print("Las ventas enero para la oficina 1 son de:", VEO1)

Las ventas enero para la oficina 1 son de: 205


In [53]:
for oficina in columnas:
    for mes in filas:
        ventas = dataframe.loc[mes, oficina]
        print(f"Ventas de {mes} en {oficina}: {ventas}")

Ventas de ventas_enero en oficina_1: 205
Ventas de ventas_febrero en oficina_1: 417
Ventas de ventas_marzo en oficina_1: 346
Ventas de ventas_enero en oficina_2: 192
Ventas de ventas_febrero en oficina_2: 160
Ventas de ventas_marzo en oficina_2: 242
Ventas de ventas_enero en oficina_3: 123
Ventas de ventas_febrero en oficina_3: 461
Ventas de ventas_marzo en oficina_3: 340
